language: java

dist: trusty

services:
  - mysql
jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew
  - mysql -e 'CREATE DATABASE hocluon;'

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
    - gradle test
before_deploy:
    - gradle build
#deploy:
#  provider: elasticbeanstalk
#  access_key_id: $ACCESSKEYID
#  secret_access_key:
#    secure: "$SECRETACCESSKEY"
#  region: "ap-southeast-1"
#  app: "hocluon"
#  env: "hocluon-stage"
#  bucket_name: "elasticbeanstalk-ap-southeast-1-454487760910"
#  zip_file: "build/libs/hocluon-0.0.1-SNAPSHOT.war"
#  skip_cleanup: true
#  on:
#    branch: master